# Generated by Django 6.0 on 2026-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller'), ('western', 'Western'), ('fantasy', 'Fantasy'), ('crime', 'Crime'), ('romance', 'Romance')], default='', max_length=30),
        ),
    ]
