# Generated by Django 6.0 on 2026-01-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_video_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
