# Generated by Django 6.0 on 2026-01-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
